language: node_js
node_js: '10'

cache:
  directories:
    - ~/.npm

script:
  - npm run prettier
  - npm run build

before_deploy:
  - vsce package

deploy:
  - provider: script
    skip_cleanup: true
    script: vsce publish --pat $VSCE_TOKEN
    on:
      tags: true
  - provider: releases
    skip_cleanup: true
    file: '*.vsix'
    file_glob: true
    api_key:
      secure: "c7zGJMRUrBTZbhfUvylVC5PTKXNFbq1Y3qx4nvcq2/BwekrxaLRCK4z4hzdg3c2QZeb2g0rtkEV7TbxQNw2QBBGIuYFua7zGwnJK200RkW6y3C43TzzbSHps2P8oEkWGwVeM7WaE6MX9d7lFqjvV5HPQyAVDRMCbrbS6Eic7CDBdL6tyBl5un+F/e8UMBWlCf9v8SaS2A+RvONXoamlWLgydOAUxaaghCLg2uw5MPoT9zUNNy8YOu+EBNn441e7hdSmgRQzChfow/yc9wFCB4UZVYdmFm0h/I42dFoovbdfDZ1/RO40fWKvjmiAiETpBybPzX1R4LqbEIUnkegp8rFQwtHpqbo1H0dWSgwJYsjCOKKPhlEBKnQfH6Je9VC0Jmv9lEeh3XKSfWIzpORj685S1+36KOl99/cX4iwYLRrT5xDcYR40/8efFCmIGl5kU5DILonY2bJhw/TB9nK0hGQkBfcYFDYWB4uubw0AJ/QO4VdbgJNjdPGIYiWB+RKXwB/OPxgXVxWbz6Gbnf7F7cET1nWGdmooTbeUR+odCFQnKmWFSFHRdry/96y4+H4FL1TL8KYf3H1nW08ViuwZz5rAGQW8bOXs5/IXskAscO9eDXAeKvzM8uuIbCA93vNaffPw08qvZYhhhXvOhMLDIeuJeMSih/VEmBYE0g+bhRgQ="
    on:
      tags: true
