language: node_js
node_js: '10'

script:
  - npm run prettier
  - npm run build

before_deploy:
  - vsce package

deploy:
  - provider: script
    skip_cleanup: true
    script: vsce publish --pat $VSCE_TOKEN
    on:
      tags: true
  - provider: releases
    skip_cleanup: true
    file: '*.vsix'
    file_glob: true
    api_key:
      secure: gp2zPwt2+JvEUnI6byTnjk0v94dwvuokZdlsEUfeaWEhs5j8yclLdTxTYMULCU8PUEwKjojD6eyCS9LXhaE4fCiKuF/Uy1lUpqspQUE1mwaNMNrHv6QqIZvhxpweaPftHeHIEkOxJHm70tUF8GqiBL7rIERs0TwJ2f9+iyDWScLmCDdk35y5ZMY9h6W4N8lw+Gd/j3QH/d1j4sbNKEMX1uOZq576e79izFPuPj1u2xJ1sasj/sh2yGvnldhOu1DKLhHgvxkaDaNDym3LSuEqrpPQ5uD6UvzIeMXuiCln6o57SrJYcI/rXrDBeatAg+4IB5PM7sv3zzIT72Cw02kl33FOY6FHWnYIGpaqxtJczWYCafMqeKR1voK5dXe5ZeXXIM5TZ6IpsVEFs1xbHvjgV1WcVVh/hUbwoUSYJMNQnOm+Y4Io6K0ysKgEfpQPVWF2gQYwN20aoXTjGagd4LF40Zt8iHTT0Mf1aFOI6J3mTtgx9MHKTFgPqTyxlh045IxHQ7ADCdeSMQhBqOwP7hObWXBTDsbyHfqa0+WC/8LTMXA6fK3AJJOmUd+n2mAj2+m6OlmipLeWiiXpqzJ4xDXYTaNkivNdyUOyf62/L0OR/lkqQlej4WJqzz+chVOJBgfciXG4q/I2rVxjv4rBiNSJ+3V37lSZlxRJPNShYm8YCWw=
    on:
      tags: true
