language: node_js
node_js: '10'

cache:
  directories:
    - ~/.npm

script:
  - npm run prettier
  - npm run build

deploy:
  - provider: script
    skip_cleanup: true
    script: npm run semantic-release
